FROM --platform=$BUILDPLATFORM golang:1.19 AS build

WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o app

FROM --platform=$TARGETOS/$TARGETARCH gcr.io/distroless/static

COPY --from=build /app/app /

CMD ["/app"]